### ISSUE TITLE
Allow using script with a template instead of just expr

### ISSUE THREAD

**Issue by jeromegn** [fornwall/rust-script#12]
Maybe this is already a feature, but I can't figure out the syntax.

I made a template called `sys.rs` and put it in the right path, but none of these work:

```
rust-script myscript -t sys
rust-script -t sys myself
```

`--expr` seems required with a `--template` flag.

**Comment by fornwall** [comment]
Perhaps this is good, to avoid making scripts non-portable?

Perhaps specifying a dependency to a local crate could provide some similar functionality for those who need it, to avoid having something rust-script specific?

**Comment by fornwall** [comment]
As said earlier, I think templates is the wrong way to go, as it complicates things and makes script non-portable. Something like https://github.com/fornwall/rust-script/issues/61 is probably preferable, so closing this one.
