### ISSUE TITLE
pub fn main() doesn't work

### ISSUE THREAD

**Issue by meluskyc** [fornwall/rust-script#14]
Looks like only these signatures are supported currently: 

```rust
let source = if source   
    .lines()   
    .any(|line| line.starts_with("fn main()") || line.starts_with("async fn main()"))
```

Could we also support `pub fn main()`? This would make it easier to develop/debug scripts from the IDE, since currently I keep them all in a cargo project.

**Comment by fornwall** [comment]
@meluskyc Thanks for pointing that out! It should be fixed in the just released `0.12.0` version - let me know if any problem remain.
