### ISSUE TITLE
Relationship to `cargo-eval`?

### ISSUE THREAD

**Issue by ErichDonGubler** [fornwall/rust-script#2]
https://github.com/reitermarkus/cargo-eval

This is a recently active fork that seems to have the exact same scope as the `cargo-eval` project. If nothing else, maybe it would be interesting to try integrating @rietermarkus' work here?

**Comment by fornwall** [comment]
Thanks for the issue!

I've added `cargo-eval` (and other related projects) to a README section: https://github.com/reitermarkus/cargo-eval/.

For now the scope is probably about the same, but rust-script will be breaking backward compatibility and be actively developed a bit more - I guess time will tell here.

> If nothing else, maybe it would be interesting to try integrating @rietermarkus' work here?

I've incorporated some changes, and will go over it in more details in coming days. Meanwhile, please let me know if there is anything special you want integrated!
