### ISSUE TITLE
Support other types of doc comments

### ISSUE THREAD

**Issue by mbhall88** [fornwall/rust-script#25]
It would be great if this tool also supported other forms of [doc comments](https://doc.rust-lang.org/stable/reference/comments.html#doc-comments). Especially the outer line doc form (`///`).

**Comment by fornwall** [comment]
Thanks @mbhall88 ! Could you try out version `0.15.0` which contains (lightly tested) support for `///` comments and let me know how it works?

**Comment by mbhall88** [comment]
Thanks @fornwall it seems to work as expected for me.
