### ISSUE TITLE
rust-script exports CARGO_TARGET_DIR to script process

### ISSUE THREAD

**Issue by soenkehahn** [fornwall/rust-script#27]
I have a `rust-script` that calls `cargo install --path .` as a child process. I expected that process to create a `target` directory, but that didn't happen. IIUC, this is because `rust-script` sets `CARGO_TARGET_DIR` to `~/.cache/rust-script/binaries`. It also seems to set a bunch of other cargo related environment variables.

I think this is a bug, since `cargo` commands from within a `rust-script` should work the same way as they would if executed from outside of a `rust-script`. I would expect `rust-script` to not modify the environment of the script process in any way. (Except maybe for some variables prefixed with `RUST_SCRIPT_` for some reason.) Or is this somehow necessary to make `rust-script` work?

**Comment by fornwall-kivra** [comment]
I believe you are right, and we should use the `--target-dir` CLI option to avoid exporting `CARGO_TARGET_DIR`.

Does https://github.com/fornwall/rust-script/pull/28 look ok and work for you?

**Comment by fornwall** [comment]
Yes, we should probably use the `--target-dir` cargo CLI option instead of exporting the `CARGO_TARGET_DIR` environment variable. Does https://github.com/fornwall/rust-script/pull/29 look ok and work for you?

Thanks for reporting!

**Comment by soenkehahn** [comment]
Hi @fornwall! Thanks for the quick fix.

Yes, just tested this in my scenario and it does work. Awesome!

It'd be great to also get this released on crates.io.

And finally, thanks a lot for working on `rust-script`, I use it all the time with great joy!

**Comment by fornwall** [comment]
Great! Version 0.16 that includes this change is now published on crates.io: https://crates.io/crates/rust-script/0.16.0

**Comment by soenkehahn** [comment]
Great! Just tested that the released version also works. Thanks a lot for the quick release! :tada:
