### ISSUE TITLE
Adding information to the README

### ISSUE THREAD

**Issue by marcospb19** [fornwall/rust-script#35]
I wonder if I can change the `README.md` file by adapting information from the `docs/README.md`, so that people don't have to leave the repository and go to the website to see what this project does.

**Comment by fornwall** [comment]
@marcospb19 That makes sense! The information in the README doesn't need to be exhaustive, but as you say it should explain what the project does.

Would you like to make a PR?

**Comment by marcospb19** [comment]
Yes! Expect a PR from me within the next weeks :+1:.

**Comment by marcospb19** [comment]
Glad this was done, sorry for not being able to implement this, I got pretty burned out recently and am having trouble getting back to open-source.
