### ISSUE TITLE
Exploring a "cargo-script" in rustup

### ISSUE THREAD

**Issue by epage** [fornwall/rust-script#46]
Would appreciate feedback on my [research and proposal](https://github.com/epage/cargo-script-mvs/discussions/15).

**Comment by epage** [comment]
Closing as this was more intend to ping people.  Let's continue any discussion in the linked issue or its repo

**Comment by epage** [comment]
FYI I've finally got back to this and created a [Pre-RFC](https://internals.rust-lang.org/t/pre-rfc-cargo-script-for-everyone/18639)

**Comment by fornwall** [comment]
@epage Thanks - I missed this previously!

Looks interesting and useful, nice work driving this.

Is the initial proposal here to bundle this by default when a user installs rust using rustup, or would it be an optional, additional install?

**Comment by epage** [comment]
Bundled by default. As I called out, there is still room for rustscript for extra caching and `--expr` flag (as I'm reserving that for the repl).

Btw I caught that windows bug because I ported the test scripts to Rust. Feel free to checkout my tests directory to see how I do it with snapbox.
