### ISSUE TITLE
Is it possible to run command (e.g. `cargo tree`) in rust-script script project directory ?

### ISSUE THREAD

**Issue by gwpl** [fornwall/rust-script#60]
Is it possible to run command (e.g. `cargo tree`) in rust-script script project directory ?
Otherwise, could support for it be added?

(sometimes running commands inside project directory is very helpful, e.g. for debugging, and having convenient way to run them, or to jump there => e.g. rust-script to print directory path, so one could do `cd "$(rust-script --project-dir script.ers)` could be very handy!

**Comment by fornwall** [comment]
[Version 0.23.0](https://github.com/fornwall/rust-script/releases/tag/0.23.0) has just been released.

There the `-p`/`--project` parameter can be used to generate the package and print the package path, without doing any build step.

This allows things such as `cargo tree --manifest-path $(rust-script -p test.rs)/Cargo.toml` or `cd "$(rust-script --package script.ers)`.

Let me know how it works!
