### ISSUE TITLE
Teach Github linguist about rust-script file

### ISSUE THREAD

**Issue by azzamsa** [fornwall/rust-script#87]
Hi.

GitHub is able to count the percentage of shell files even if they don't have `.sh` or simmilar extenison.

![image](https://user-images.githubusercontent.com/17734314/228996053-8bad499b-1f3e-4970-81a9-2daa57e6ff43.png)

![image](https://user-images.githubusercontent.com/17734314/228996114-9e87cac3-f929-4dfe-a23a-367b4ad7e99d.png)

Is it possible for us to teach GitHub about rust-script file based on `#!/usr/bin/env rust-script` even if it doesn't have `.rs` extension?

![image](https://user-images.githubusercontent.com/17734314/228996356-93a978c5-2b42-4eba-ad73-f79741f768dc.png)

I think we should start from [Adding an extension to a language in linguist/CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language)

Thank you for rust-script :heart:

**Comment by fornwall** [comment]
Thanks for the suggestion!

I created https://github.com/github/linguist/pull/6354 - let's see what the maintainers say.

**Comment by fornwall** [comment]
This is on track to be included in the next linguist release - https://github.com/github/linguist/pull/6354#pullrequestreview-1369332349.

Closing this as the work has been done, follow https://github.com/github/linguist/pull/6354 for progress updates.

Once again, thanks for the suggestion @azzamsa !
